
# This workflow builds a project afters tests including e2e and deploys to Rancher using Docker image
# For more information see:
#  - https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#  - https://github.com/marketplace/actions/build-and-push-docker-images
#  - https://github.com/marketplace/actions/rancher-redeploy-workload

name: CI and CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'
      - name: Test with NPM
        run: |
          npm install
          npm run lint
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: success() && ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        if: success() && ${{ github.event_name == 'push' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            rhizomik/rhizomer-eye:${{ github.sha }}
            rhizomik/rhizomer-eye:latest
